
#include <stddef.h>

char* level2[] = {
    "82",
    "90",
    "17",
    "5",
    "25",
    "0",
    "164",
    "0",
    "         *                                                                        ",
    "                                                                                  ",
    "                                                                                  ",
    "                                                                                  ",
    "                                                                                  ",
    "  def                                   stpppppppppppppppppppppppppppppqr         ",
    "  ghi                                 stpppppppppppppppppppppppppppppppppqr       ",
    "  jkl                               stpppppppppppppppppppppppppppppppppppppqr     ",
    "pppppppqr                         stpppppppppppppppppppppppppppppppppppppppppppppp",
    "pppppppppqr                     stpppppppppppppppppppppppppppppppppppppppppppppppp",
    "pppppppppppqr                 stpppppppppppppppppppppppppppppppppppppppppppppppppp",
    "pppppppppppppqr             stpppppppppppppppppppppppppppppppppppppppppppppppppppp",
    "pppppppppppppppqr           pppppppppppppppppppppppppppppppppppppppppppppppppppppp",
    "pppppppppppppppppqr         pppppppppppppppppppppppppppppppppppppppppppppppppppppp",
    "ppppppppppppppppppp         pppppppppppppppppppppppppppppppppppppppppppppppppppppp",
    "ppppppppppppppppppp         pppppppppppppppppppppppppppppppppppppppppppppppppppppp",
    "ppppppppppppppppppp         pppppppppppppppppppppppppppppppppppppppppppppppppppppp",
    "ppppppppppppppppppp         pppppppppppppppppppppppppppppppppppppppppppppppppppppp",
    "ppppppppppppppppppp         pppppppppppppppppppppppppppppppppppppppppppppppppppppp",
    "ppppppppppppppppppp         pppppppppppppppppppppppppppppppppppppppppppppppppppppp",
    "ppppppppppppppppppp         pppppppppppppppppppppppppppppppppppppppppppppppppppppp",
    "ppppppppppppppppppp         pppppppppppppppppppppppppppppppppppppppppppppppppppppp",
    "ppppppppppppppppppp         pppppppppppppppppppppppppppppppppppppppppppppppppppppp",
    "ppppppppppppppppppp         pppppppppppppppppppppppppppppppppppppppppppppppppppppp",
    "ppppppppppppppppppp         pppppppppppppppppppppppppppppppppppppppppppppppppppppp",
    "ppppppppppppppppppp#########pppppppppppppppppppppppppppppppppppppppppppppppppppppp",
    "ppppppppppppppppppp         xppppppppppppppppppppppppppppppppppppppppppppppppppppp",
    "ppppppppppppppppppu          wxppppppppppppppppppppppppppppppppppppppppppppppppppp",
    "ppppppppppppppppuv            \\wxppppppppppppppppppppppppppppppppppppppppppppppppp",
    "ppppppppppppppuv              ]^_wxppppppppppppppppppppppppppppppppppppppppppppppp",
    "ppppppppppppuv                     wpppppppppppppppppppppppppppppppppppppppppppppp",
    "ppppppppppuv[       *               pppppppppppppppppppppppppppppppppppppppppppppp",
    "ppppppppuvXYZ                       pppppppppppppppppppppppppppppppppppppppppppppp",
    "pppppppv                            pppppppppppppppppppppppppppppppppppppppppppppp",
    "ppppppp                             pppppppppppppppppppppppppppppppppppppppppppppp",
    "ppppppp                             pppppppppppppppppppppppppppppppppppppppppppppp",
    "ppppppp                           stpppppppppppppppppppppppppppppppppppppppppppppp",
    "pppppppr                        stpppppppppppppppppppppppppppppppppppppppppppppppp",
    "ppppppppqr                    stpppppppppppppppppppppppppppppppppppppppppppppppppp",
    "ppppppppppqr                stpppppppppppppppppppppppppppppppppppppppppppppppppppp",
    "ppppppppppppqr       `a   stpppppppppppppppppppppppppppppppppppppppppppppppppppppp",
    "ppppppppppppppqr m   bc stpppppppppppppppppppppppppppppppppppppppppppppppppppppppp",
    "pppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp",
    NULL};
